name: Sitemap Generator

on:
  push:
    paths:
      - 'app-config.json'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: "${{ secrets.SITEMAP_TOKEN }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        git remote rm origin
        git remote add origin https://mastaleru:$GITHUB_TOKEN@github.com/PrivateSky/privatesky-xyz.git

        npm run generate-sitemap --if-present
        git add sitemap.xml
        git commit -m "GithubRunner:sitemap.xml was updated"
        echo "here";
        echo $SITEMAP_TOKEN
        echo GITHUB_TOKEN
        git config url."git@github.com:".insteadOf "https://github.com/"

        git push --dry-run
      env:
        CI: true
        SITEMAP_TOKEN: ${{ secrets.SITEMAP_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}