name: Sitemap Generator

on:
  push:
    paths:
      - 'app-config.json'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        git checkout sitemap-test
        npm run generate-sitemap --if-present
        git config --global user.email "mastaleru.rafael@gmail.com"
        git config --global user.name "Mastaleru"
        git add sitemap.xml
        git commit -m "GithubRunner:sitemap.xml was updated"
        git status
        git push
      env:
        CI: true
